---
title: "R Notebook"
output: html_notebook
---

This is to do validated and get output of single GAMM models

#### Packages
```{r}
here::i_am("Scripts/Rmd_Scripts/process_GAMMS_single.Rmd")
library(tidyverse)
library(tmap)
library(mgcv)
library(gamm4)
library(mgcViz)
library(gstat)
library(knitr)
library(knitrProgressBar)
library(tictoc)
library(here)
library(conflicted)
conflicts_prefer(dplyr::filter)
conflicts_prefer(dplyr::select)
conflicts_prefer(knitrProgressBar::progress_estimated)
# there is a same-named function in dplyr, check it out
```
#### Functions
```{r}
# From https://stackoverflow.com/questions/71252509/is-there-a-way-to-get-progress-information-whan-a-chunk-is-running-in-rmarkdown

slow_function <- function(i, .pb=NULL) {  
  update_progress(.pb)  
  Sys.sleep(0.5)  
  i  
}
# create an R6 progress object for
# the number of loops/iterations in the target chunk
```

#### File Paths
```{r}

#data_path <- paste0("./Data/Processed_Data/Spatial/", params$dataset, ".rds")
data_path <- paste0("./Data/Processed_Data/Spatial/all_species.rds")
out_path <-  here("Output/Spatial/GAM")
if(!dir.exists(out_path)) dir.create(out_path)
```

#### Datasets for gamms
```{r}
my_gamm <- readRDS(paste0(here(out_path), "/GAMM_all_species/gamm_all_species_exp_gaus2.rds"))



data <- readRDS(data_path)
```


#### for each dataset, prepare data for gamm input, remove transects that are duplicates for x and y coordinates (keep first one)
```{r}
site.by.species <- data$site.by.species
site.by.env <- data$site.by.env
site.by.xy <- data$site.by.xy
sites <- data$sites

# assemble xy, environmental vars and richness for analysis
site.by.env.xy.richness <- cbind(site.by.env, rowSums(site.by.species)) %>%
  cbind(site.by.xy) %>%
rename(species.richness = 'rowSums(site.by.species)')

#inspect duplicates to see how they arise
dup_xy <- sites %>%
  mutate(xy = paste(x,y)) %>%
group_by(xy) %>% 
  filter(n() > 1)

print(kable(dup_xy, caption = "Transects with same coords"))
  
#remove duplicates for rows with the same x and y coordinates
gamm_input <- site.by.env.xy.richness %>%
  mutate(xy = paste(x,y)) %>%
  distinct(xy, .keep_all = TRUE)

hist(gamm_input$species.richness)
```



```{r}
(summary(my_gamm$gam))
#(summary(my_gamm$lme)) What does this mean?
par(mfrow = c(2, 2))
plot(my_gamm$gam, residuals = TRUE, shade = TRUE, 
     shift = coef(my_gamm$gam)[1])

#save to do custom plots later
pdata <- plot(my_gamm$gam, residuals = TRUE, shade = TRUE, 
     shift = coef(my_gamm$gam)[1])



par(mfrow = c(2, 2))
(gam.check(my_gamm$gam))

acf(residuals(my_gamm$lme,type="normalized"),main="standardized residual ACF")

print("Overall concurvity")
kable(concurvity(my_gamm$gam, full = TRUE), digits = 2)
print("worst")
kable(concurvity(my_gamm$gam, full = FALSE)$worst, digits = 2)
print("observed")
kable(concurvity(my_gamm$gam, full = FALSE)$observed, digits = 2)
print("estimate")
kable(concurvity(my_gamm$gam, full = FALSE)$estimate, digits = 2)
```
### Residual plots 
Following https://stats.stackexchange.com/questions/331716/gamm-residuals-patterns-temporal-and-spatial
See Zuur et al. 2009 chapter 18
```{r}
resvals <- resid(my_gamm$lme, type = "normalized")
expvals <- fitted(my_gamm$lme)
obsvals <- gamm_input$species.richness

par(mfrow = c(2, 2))
  stats::qqnorm(resvals)
  qqline(resvals)
  
  plot(resvals~expvals, xlab = "Fitted values", ylab = "Residuals",
   cex = 0.3)
  
  hist(resvals)
  
  plot(obsvals ~ expvals, xlab = "Fitted values", ylab = "Observed values",
   cex = 0.3)
```
#mgcViz smooth plots in case I want them later
```{r}

# viz_as <- getViz(my_gamm$gam)
# 
# for (i in 1:length(viz_as$sp))
# {
# p1 <- plot(sm(viz_as, i)) +
#   l_fitLine(colour = "red") + l_rug(mapping = aes(x=x, y=y), alpha = 0.8) +
#     l_ciLine(mul = 1.96, colour = "blue", linetype = 2) + #mul is parameter to multiply SE for CL
#     l_points(shape = 19, size = 1, alpha = 0.1) + theme_classic()
# print(p1)
# }

```

