---
title: "MSGDM supplementary materials"
author: "JG Rodger"
date: "2024-06-18"
output: html_document
---



###Deviance explained

#### All Butterfly Species, Simpson
```{r  message = FALSE}
print_csv("./Output/Spatial/msgdms/all_species_Simpson/figs_tables/deviance_table.csv", tab_no = "SM1", tab_cap = "Deviance explained by MSGDMs for Simpson-Normalized zeta diversity for All Butterfly Species", my_dig = 3)
```

```{r message = FALSE}
print_csv("./Output/Spatial/msgdms/all_species_Simpson//figs_tables/variance_partitioning_table.csv", tab_no = "SM2", tab_cap = "Variation partitioning for MSGDMs for Simpson-Normalized zeta diversity for All Species", my_dig = 3)
```


#### Wider Countryside Species, Simpson
```{r  message = FALSE}
print_csv("./Output/Spatial/msgdms/wc_Simpson/figs_tables/deviance_table.csv", tab_no = "SM3", tab_cap = "Deviance explained by MSGDMs for Simpson-Normalized zeta diversity for Wider Countryside Species", my_dig = 3)
```

```{r  message = FALSE}
print_csv("./Output/Spatial/msgdms/wc_Simpson//figs_tables/variance_partitioning_table.csv", tab_no = "SM4", tab_cap = "Variation partitioning for MSGDMs for Simpson-Normalized zeta diversity for Wider Countryside Species", my_dig = 3)
```

#### Habitat Specialists, Simpson
```{r  message = FALSE}
print_csv("./Output/Spatial/msgdms/hs_no_zeros_Simpson/figs_tables/deviance_table.csv", tab_no = "SM5", tab_cap = "Deviance explained by MSGDMs for Simpson-Normalized zeta diversity for Habitat Specialists", my_dig = 3)
```

```{r message = FALSE}
print_csv("./Output/Spatial/msgdms/hs_no_zeros_Simpson//figs_tables/variance_partitioning_table.csv", tab_no = "SM6", tab_cap = "Variation partitioning for MSGDMs for Simpson-Normalized zeta diversity for Habitat Specialists", my_dig = 3)
```

#### All Butterfly Species, Sorensen
```{r  message = FALSE}
print_csv("./Output/Spatial/msgdms/all_species_Sorensen/figs_tables/deviance_table.csv", tab_no = "SM7", tab_cap = "Deviance explained by MSGDMs for Sorensen-Normalized zeta diversity for All Species", my_dig = 3)
```

```{r  message = FALSE}
print_csv("./Output/Spatial/msgdms/wc_Sorensen//figs_tables/variance_partitioning_table.csv", tab_no = "SM8", tab_cap = "Variation partitioning for MSGDMs for Sorensen-Normalized zeta diversity for Wider Countryside Species", my_dig = 3)
```


#### Wider Countryside Species, Sorensen
```{r message = FALSE}
print_csv("./Output/Spatial/msgdms/wc_Sorensen/figs_tables/deviance_table.csv", tab_no = "SM9", tab_cap = "Deviance explained by MSGDMs for Sorensen-Normalized zeta diversity for Wider Countryside Species", my_dig = 3)
```

```{r message = FALSE}
print_csv("./Output/Spatial/msgdms/wc_Sorensen//figs_tables/variance_partitioning_table.csv", tab_no = "SM10", tab_cap = "Variation partitioning for MSGDMs for Sorensen-Normalized zeta diversity for Wider Countryside Species", my_dig = 3)
```


#### Habitat Specialists, Sorensen
```{r  message = FALSE}
print_csv("./Output/Spatial/msgdms/hs_no_zeros_Sorensen/figs_tables/deviance_table.csv", tab_no = "SM11", tab_cap = "Deviance explained by MSGDMs for Sorensen-Normalized zeta diversity for Habitat Specialists", my_dig = 3)
```


```{r  message = FALSE}
print_csv("./Output/Spatial/msgdms/hs_no_zeros_Sorensen//figs_tables/variance_partitioning_table.csv", tab_no = "SM12", tab_cap = "Variation partitioning for MSGDMs for Sorensen-Normalized zeta diversity for Habitat Specialists", my_dig = 3)
```


