---
title: "R Notebook"
output: html_notebook
---

```{r}
here::i_am("Scripts/Rmd_Scripts/butterfly_maps.Rmd")
library(tidyverse)
library(viridis)
library(terra)
library(tidyterra)
library(sf)
library(spatstat)
library(ggplot2)
library(gridExtra)
library(here)
```

#### Load basemap and butterfly data
```{r}
# Basemap without outlying islands
gb <- readRDS(here("./Data./Maps./gb_multipolygon_simplified.rds"))

#All species data
as_data <- readRDS(here("./Data/Processed_Data/Spatial/all_species.rds"))

sites <- as_data$sites %>%
  rename(as.richness = richness)

# Habitat generalists
wc_data <- readRDS(here("./Data/Processed_Data/Spatial/wc.rds"))


#Habitat specialists
hs_data <- readRDS(here("./Data/Processed_Data/Spatial/hs.rds"))

# load environmental data
comb <- readRDS(here("./Data/Processed_Data/Spatial/map_all_env_vars.rds"))
```

#### add species richness for habitat specialists and generalists to site data
```{r}
any(rownames(sites) != rownames(wc_data$site.by.species))
any(rownames(sites) != rownames(hs_data$site.by.species))

sites <- sites %>%
  mutate(wc.richness = rowSums(wc_data$site.by.species),
         hs.richness = rowSums(hs_data$site.by.species))
```


### squares and hexagons of point density, adapted from https://r-graph-gallery.com/329-hexbin-map-for-distribution.html
```{r}
#rectangle
rect_dens <- ggplot() + 
    geom_sf(data = gb) +
  geom_bin2d(bins=30, data = sites, aes(x = x, y = y)) +
    scale_fill_viridis(name="Sites", 
      breaks = c(0, 1,2, 5,10,15,20, 25, 30)) + 
  labs(x = "", y = "") + 
  theme(
  axis.text.x = element_blank(),
  axis.text.y = element_blank(),
  axis.ticks = element_blank())

#hex
hex_dens <- ggplot() + 
    geom_sf(data = gb) +
  geom_hex(bins=30, data = sites, aes(x = x, y = y)) +
    scale_fill_viridis_b(name="Sites", 
      breaks = c(0,2, 5,10,15,20, 25, 30)) + 
  labs(x = "", y = "") + 
  theme(
  axis.text.x = element_blank(),
  axis.text.y = element_blank(),
  axis.ticks = element_blank(), 
  legend.direction = "horizontal", 
  legend.position = "bottom") +
  guides(fill = guide_colorbar(title = "Sites", 
                             theme(legend.title.position = "top",
                                  legend.text.position = "bottom")))


rect_dens
hex_dens



png(filename =  paste0(here("Output/Spatial/Figures/Hex_dens_transects.png/")))
hex_dens
dev.off()
```

```{r}
hist(sites$as.richness)
hist(sites$wc.richness)
hist(sites$hs.richness)
```


```{r}
# modified above plot along lines suggested by answer https://stackoverflow.com/questions/74818772/r-how-to-fill-geom-hex-with-a-numerical-value-and-heat-scale-it


# note, by default interals are left-open and right-closed, ie they do not include lower endpoint but do include right endpoint

as_richness <- ggplot() + 
    geom_sf(data = gb) +
  stat_summary_hex(
    bins=30, 
    data = sites, 
    aes(x = x, y = y, z = as.richness)) + #the mean is taken by default
    scale_fill_viridis_b(name="AS",
    breaks = c(5, 10, 15, 20, 25, 30, 35)) + 
  labs(x = "", y = "") + 
  theme(
  axis.text.x = element_blank(),
  axis.text.y = element_blank(),
  axis.ticks = element_blank(), 
  legend.direction = "horizontal", 
  legend.position = "bottom") +
  guides(fill = guide_colorbar(title = "AS", 
                             theme(legend.title.position = "top",
                                  legend.text.position = "bottom")))
as_richness


```
```{r}

wc_richness <- ggplot() + 
    geom_sf(data = gb) +
  stat_summary_hex(
    bins=30,
    data = sites, 
    aes(x = x, y = y, z = wc.richness)) + #the mean is taken by default
    scale_fill_viridis_b(name="HG",
    breaks = c(5, 10, 15, 20, 25, 30, 35)) + 
  labs(x = "", y = "") + 
  theme(
  axis.text.x = element_blank(),
  axis.text.y = element_blank(),
  axis.ticks = element_blank(), 
  legend.direction = "horizontal", 
  legend.position = "bottom") +
  guides(fill = guide_colorbar(title = "HG", 
                             theme(legend.title.position = "top",
                                  legend.text.position = "bottom")))

wc_richness
```

```{r}

hs_richness <- ggplot() + 
    geom_sf(data = gb) +
  stat_summary_hex(
    bins=30,
    data = sites, 
    aes(x = x, y = y, z = hs.richness)) + #the mean is taken by default
    scale_fill_viridis_b(name = "HS",
    breaks = c(0, 1 , 2, 4, 6, 8, 10)) + 
  labs(x = "", y = "") + 
  theme(
  axis.text.x = element_blank(),
  axis.text.y = element_blank(),
  axis.ticks = element_blank(), 
  legend.direction = "horizontal", 
  legend.position = "bottom") +
  guides(fill = guide_colorbar(title = "HS", 
                             theme(legend.title.position = "top",
                                  legend.text.position = "bottom")))

hs_richness
```
```{r}
all_hex <- grid.arrange(hex_dens, as_richness, wc_richness, hs_richness, ncol = 4, nrow = 1)

plot(all_hex)

#another way to save
# ggsave(
#   here("Output/Spatial/Figures/Hex_dens_transects_richness.png/"),
#   all_hex,
#   units = "mm",
#   width = 200,
#   dpi = 1200
# )

png(filename =  here("Output/Spatial/Figures/Hex_dens_transects_richness.png/"), pointsize=10, width=1400, height=960, res=300)
plot(all_hex)
dev.off()

#test

```






#### Plot env vars and save pngs for figures
```{r}
# two sets of vars to be plotted 
comb1 <- select(comb, x, y,  mean.ann.temp, topographic.wetness, ph, total.n)
comb2 <- select(comb, x, y,  log10.mean.ann.rain, tree.density, log10.pesticide.risk, log10.humans)
comb3 <- select(comb, x, y,  mean.ann.temp, topographic.wetness, ph, total.n, log10.mean.ann.rain, tree.density, log10.pesticide.risk, log10.humans)

comb1 <- rast(comb1, crs = "EPSG:27700")
comb2 <- rast(comb2, crs = "EPSG:27700")
comb3 <- rast(comb3, crs = "EPSG:27700")

plot(comb1)
plot(comb2)
plot(comb3)

```



```{r}
# this worked for individual plots but not multipanel plot
theme_j1 <- function(){ 
    font <- "Georgia"   #assign font family up front
    
    theme_grey() %+replace%    #replace elements we want to change
    
    theme(
      
   legend.position = c(.8, .75),
             legend.background = element_rect(fill="grey", 
                                size=0.5, linetype="solid")
    )
}
```


```{r}
#copy and paste because I can't work out how to do inside a function


# mean.ann.temp
temp_rast <- comb3 %>%
  select(mean.ann.temp)

temp_plot <- ggplot() +
  geom_spatraster(data = temp_rast) +
  scale_fill_viridis_c(name="Mean Annual Temperature")  + 
  theme(
  axis.text.x = element_blank(),
  axis.text.y = element_blank(),
  axis.ticks = element_blank(), 
  legend.direction = "horizontal", 
  legend.position = "bottom") +
  guides(fill = guide_colorbar(title = "Mean Annual Temperature", 
                             theme(legend.title.position = "top",
                                  legend.text.position = "bottom")))


# topographic.wetness
wet_rast <- comb3 %>%
  select(topographic.wetness)


wet_plot <- ggplot() +
  geom_spatraster(data = wet_rast) +
  scale_fill_viridis_c(name="Topographical Wetness") + 
  theme(
  axis.text.x = element_blank(),
  axis.text.y = element_blank(),
  axis.ticks = element_blank(), 
  legend.direction = "horizontal", 
  legend.position = "bottom") +
  guides(fill = guide_colorbar(title = "Topographical Wetness", 
                             theme(legend.title.position = "top",
                                  legend.text.position = "bottom")))


#ph
ph_rast <- comb3 %>%
  select(ph)

ph_plot <- ggplot() +
  geom_spatraster(data = ph_rast) +
  scale_fill_viridis_c(name="pH")  + 
  theme(
  axis.text.x = element_blank(),
  axis.text.y = element_blank(),
  axis.ticks = element_blank(), 
  legend.direction = "horizontal", 
  legend.position = "bottom") +
  guides(fill = guide_colorbar(title = "pH", 
                             theme(legend.title.position = "top",
                                  legend.text.position = "bottom")))


#total.n

n_rast <- comb3 %>%
  select(total.n)

n_plot <- ggplot() +
  geom_spatraster(data = n_rast) +
  scale_fill_viridis_c(name="Total Nitrogen Deposition")  + 
  theme(
  axis.text.x = element_blank(),
  axis.text.y = element_blank(),
  axis.ticks = element_blank(), 
  legend.direction = "horizontal", 
  legend.position = "bottom") +
  guides(fill = guide_colorbar(title = "Total Nitrogen Deposition", 
                             theme(legend.title.position = "top",
                                  legend.text.position = "bottom")))


# log10.mean.ann.rain 

prec_rast <- comb3 %>%
  select(log10.mean.ann.rain)

prec_plot <- ggplot() +
  geom_spatraster(data = prec_rast) +
  scale_fill_viridis_c(name="Log Annual Precipitation") + 
  theme(
  axis.text.x = element_blank(),
  axis.text.y = element_blank(),
  axis.ticks = element_blank(), 
  legend.direction = "horizontal", 
  legend.position = "bottom") +
  guides(fill = guide_colorbar(title = "Log Annual Precipitation", 
                             theme(legend.title.position = "top",
                                  legend.text.position = "bottom")))


# tree.density
tree_rast <- comb3 %>%
  select(tree.density)

tree_plot <- ggplot() +
  geom_spatraster(data = tree_rast) +
  scale_fill_viridis_c(name="Tree Density")  + 
  theme(
  axis.text.x = element_blank(),
  axis.text.y = element_blank(),
  axis.ticks = element_blank(), 
  legend.direction = "horizontal", 
  legend.position = "bottom") +
  guides(fill = guide_colorbar(title = "Tree Density", 
                             theme(legend.title.position = "top",
                                  legend.text.position = "bottom")))


# log10.pesticide.risk
pest_rast <- comb3 %>%
  select(log10.pesticide.risk)

pest_plot <- ggplot() +
  geom_spatraster(data = pest_rast) +
  scale_fill_viridis_c(name="Log Pesticide Risk Quotient")  + 
  theme(
  axis.text.x = element_blank(),
  axis.text.y = element_blank(),
  axis.ticks = element_blank(), 
  legend.direction = "horizontal", 
  legend.position = "bottom") +
  guides(fill = guide_colorbar(title = "Log Pesticide Risk Quotient", 
                             theme(legend.title.position = "top",
                                  legend.text.position = "bottom")))


# log10.humans
humans_rast <- comb3 %>%
  select(log10.humans)

humans_plot <- ggplot() +
  geom_spatraster(data = humans_rast) +
  scale_fill_viridis_c(name="Log Human Density")  + 
  theme(
  axis.text.x = element_blank(),
  axis.text.y = element_blank(),
  axis.ticks = element_blank(), 
  legend.direction = "horizontal", 
  legend.position = "bottom") +
  guides(fill = guide_colorbar(title = "Log Human Density", 
                             theme(legend.title.position = "top",
                                  legend.text.position = "bottom")))

```

```{r}
all_env <- grid.arrange(temp_plot, wet_plot, ph_plot, n_plot, 
                        prec_plot, tree_plot, pest_plot, humans_plot, 
                        widths = rep(4, 4),
                        ncol = 4, nrow = 2)

plot(all_env)

# ggsave(
#   here("Output/Spatial/Figures/Hex_dens_transects_richness.png/"),
#   all_env,
#   units = "mm",
#   width = 300,
#   dpi = 1200
# )

png(file = here("Output/Spatial/Figures/all_env_vars.png/"))
plot(all_env)
dev.off()

```