---
title: "R Notebook"
output: html_notebook
---



## setup
```{r}

#The here package enables easy file referencing by using the top-level directory of a file project to easily build file paths."
#about here package: https://here.r-lib.org/articles/here.html
#https://github.com/jennybc/here_here
#by running this before loading the package, we can get a message to check the correct root is being used
here::i_am("Scripts/Rmd_Scripts/butterflies_combine_env_data.Rmd")

library(tidyverse)
library(conflicted)
library(terra)
library(sf)
library(tmap)
library(here)

conflicts_prefer(dplyr::filter)

# library(readr)
# 
# library(segmented)
# 
# library(sgo)


```


## Load data
```{r}

#load polygon to use to crop as map extents a bit different

gb <- readRDS(here("./Data/Input_Environmental_Data/gb_multipolygon.rds"))

str(gb, max.level = 1)

crs(gb)

#r markdowns and notebooks default to using the directory where they are stored as the working directory


#site by species matrix

# Still need to replace this with occurrence over multiple years
site.by.species <- readRDS(here("./Data/Processed_Data/site_by_obs_5_year_pres_abs.rds"))

#get site by xy
sites <- readRDS(here("./Data/Processed_Data/processed_5_year_sites.rds"))

species <-  readRDS(here("./Data/Processed_Data/species_5_year.rds"))

site.by.humans <- readRDS(here("./Data/Input_Environmental_Data/human_popn.rds"))


site.by.ph <- readRDS(here("./Data/Input_Environmental_Data/ph_1km_df.rds"))

site.by.trees <-  readRDS(here("./Data/Input_Environmental_Data/trees_1km_df.rds"))

#site.by.conifer.dominance <-  readRDS(here("./Data/Input_Environmental_Data/conifer_dominance_1km_df.rds"))

site.by.nitrogen <- readRDS(here("./Data/Input_Environmental_Data/nitro.rds"))

site.by.pesticide.risk <- readRDS(here("./Data/Input_Environmental_Data/pesticide_df.rds"))

site.by.wetness <- readRDS(here("./Data/Input_Environmental_Data/topographic_wetness_df.rds"))

site.by.temp <- readRDS(here("./Data/Input_Environmental_Data/mean_temp_df.rds"))

site.by.prec <- readRDS(here("./Data/Input_Environmental_Data/mean_prec_df.rds"))



surveys.site.year <- readRDS(here("./Data/Processed_Data/surveys_site_year.rds"))

#sites.with.40 <- readRDS(here("./Data/Processed_Data/sites_with_at_least_40_years.rds"))


```

#as a check, turn all input into spatrast and plot
```{r}



# a function to make raster, crop and plot it

#Always does first layer only if multiple layers

plot.df <- function(df, ext){
  rast <- rast(df, crs = "EPSG:27700")
rast <- crop(rast[[1]], ext)
plot(rast)
}


plot.df(df = site.by.temp, ext = gb)


plot.df(df = site.by.prec, ext = gb)

plot.df(df = site.by.wetness, ext = gb)



plot.df(df = site.by.ph, ext = gb)


plot.df(df = site.by.trees, ext = gb)

plot.df(df = site.by.nitrogen, ext = gb)


plot.df(site.by.pesticide.risk, ext = gb)

plot.df(df = site.by.humans, ext = gb)




```
```{r}

#now we need the transformed land cover composition of the grid cells
log10_plusone <- function(x)
{log10(x + 1)}


site.by.log10.pesticide.risk <- site.by.pesticide.risk %>%
  mutate(log10.pesticide.risk = log10_plusone(pest)) %>%
  select(x, y, log10.pesticide.risk, ngr.1km) #also gets it in correct order



site.by.log10.humans <- site.by.humans %>%
  mutate(log10.humans = log10_plusone(gbr_pd_2017_1km)) %>%
  select(x, y, log10.humans, ngr.1km) #also gets it in correct order


plot.df(site.by.log10.pesticide.risk, ext = gb)


plot.df(site.by.log10.humans, ext = gb)
```

## get variable names as desired in dataframes

```{r}
#get site as a variable in the sites and site by species data frames



rownames(site.by.species) <- paste("site", rownames(site.by.species), sep = "_")


site.by.temp <- site.by.temp %>%
  rename(mean.ann.temp = mean)

site.by.prec <- site.by.prec %>%
  rename(mean.ann.rain = mean) %>%
  select(-c(x,y))

site.by.ph <- site.by.ph %>%
  select(-c(x, y)) %>%
  rename(ph = ph_idw)

site.by.log10.humans <- site.by.log10.humans %>%
  select(-c(x, y))

site.by.trees <- site.by.trees %>%
  rename(tree.density = tree.cover.density)%>%
  select(-c(x, y)) 

#site.by.conifer.dominance <-select(site.by.conifer.dominance, -c(x, y))


site.by.nitrogen <-select(site.by.nitrogen, total.n, ngr.1km)


site.by.pesticide.risk <- site.by.pesticide.risk %>%
  rename(pesticide.risk = pest)%>%
  select(-c(x, y)) 


site.by.log10.pesticide.risk <- site.by.log10.pesticide.risk %>%
  select(-c(x, y)) 




site.by.wetness <- site.by.wetness %>%
  rename(topgraphic.wetness = Band1) %>%
  select(-c(x,y))


```

#filter site data to selected sites

#sometimes more than one site per gridref!
```{r}
#to keep this to sort by after merging
sites<- sites %>%
  mutate(site.no = site,
         site = paste("site", sites$site, sep = "_"))

nrow(sites)


site.by.env <- sites %>%
  select(site.no, site, ngr.1km)

site.by.temp <- site.by.temp %>% #rearrange columns
  select(c(ngr.1km, x, y, mean.ann.temp))


site.by.env <- site.by.env %>%
  merge(site.by.temp, by = "ngr.1km")

nrow(site.by.env)

site.by.env <- merge(site.by.env, site.by.prec, by = "ngr.1km")

nrow(site.by.env)



site.by.env <- merge(site.by.env, site.by.wetness, by = "ngr.1km")

nrow(site.by.env)

site.by.env <- merge(site.by.env,site.by.ph,  by = "ngr.1km")

nrow(site.by.env)


site.by.env <- merge(site.by.env, site.by.nitrogen, by = "ngr.1km")

nrow(site.by.env)

site.by.env <- merge(site.by.env, site.by.log10.humans, by = "ngr.1km") 


nrow(site.by.env)

site.by.env <- merge(site.by.env, site.by.pesticide.risk, by = "ngr.1km")

nrow(site.by.env)

site.by.env <- merge(site.by.env, site.by.log10.pesticide.risk, by = "ngr.1km")

nrow(site.by.env)

site.by.env <- merge(site.by.env, site.by.trees, by = "ngr.1km")



nrow(site.by.env)


#order by site.number

site.by.env <- site.by.env[order(site.by.env$site.no), ]

#remove site.number
site.by.env <- select(site.by.env, -site.no)

```



## Plot  Sites
```{r}

plot.points <- st_as_sf(site.by.env, coords=c("x","y"), remove = FALSE, crs = 27700)#I want to keep coords in the dataframe

#get a set of points for each unique grid cell

print("sites")
nrow(plot.points)

basemap <-tm_shape(gb) +
  tm_borders()
pointsmap <- basemap + 
tm_shape(plot.points) +
  tm_symbols(size = 0.05, col = "blue")

pointsmap2 <- basemap + 
tm_shape(plot.points) +
  tm_symbols(size = 0.5, col = "blue")


print(pointsmap)
print(pointsmap2)


#isle of man and channell islands should probably be excluded
```


```{r}
hist(site.by.env$mean.ann.temp)
hist(site.by.env$mean.ann.rain)
hist(site.by.env$topgraphic.wetness )#note typo to be corrected
hist(site.by.env$ph)
hist(site.by.env$tree.density)
hist(site.by.env$log10.humans)
hist(site.by.env$total.n )


hist(site.by.env$pesticide.risk)
hist(site.by.env$pesticide.risk, breaks = 100)
hist(site.by.env$log10.pesticide.risk, breaks = 100)


```
```{r}
site.by.env <- site.by.env %>%
  select(-pesticide.risk)
```


```{r}
cor(site.by.env[, 4:12], method = "pearson")
```


```{r}
cor(site.by.env[, 4:12], method = "spearman")


```
## Obtain final site by env, site.by.xy, 

```{r}

#throws error
#site.by.env <- column_to_rownames(site.by.env, var = "site")

rownames(site.by.env) <- site.by.env$site

site.by.xy <- select(site.by.env, x, y)


site.by.env <- select(site.by.env, -c(ngr.1km, site, x, y))

site.by.species <- filter(site.by.species,
                          rownames(site.by.species) %in% rownames(site.by.env))


sites<- filter(sites, site %in% rownames(site.by.env))
```



## to do:  change this to the 2015-2019 selection of sites
## look at the percentage of cells that each species occurs in
```{r}
check <- data.frame(colMeans(site.by.species))
  names(check) <- "occurrence"
check <- check %>%
  mutate(var.occurence = occurrence*(1-occurrence))

check
```
```{r}
#just keep sites in dataset
sites <- filter(sites,
                site %in% rownames(site.by.species))

head(site.by.species)

head(site.by.env)

head(site.by.xy)
```

## filter

```{r}

```


```{r}

data.5.years <- list(species, sites, site.by.species, site.by.env, site.by.xy)

names(data.5.years) <- c("species", "sites", "site.by.species", "site.by.env", "site.by.xy")


write_rds(data.5.years, file = here("./Data/Processed_Data/butterfly.msgdm.data.5.years.rds"))

```

