---
title: "R Notebook"
output: html_notebook
---


#### Packages
```{r}
here::i_am("Scripts/Rmd_Scripts/GAM_analyses.Rmd")
library(tidyverse)
library(sf)
library(sp)
library(terra)
library(mgcv)
library(knitr)
library(mgcViz)
library(gstat)
library(knitrProgressBar)
library(tictoc)
library(here)
library(conflicted)
conflicts_prefer(dplyr::filter)
conflicts_prefer(dplyr::select)
conflicts_prefer(knitrProgressBar::progress_estimated)

# there is a same-named function in dplyr, check it out
```

#### Functions
```{r}
# A function for plotting gam relationships with my preferences


my.plot.gam <- function(gam_object){
plot(gam_object, residuals = TRUE, seWithMean = TRUE, shade = TRUE, shift = coef(gam_object)[1], pages = 2) 
}
```

#### File Paths
```{r}
data_path <- paste0("./Data/Processed_Data/Spatial/", "hs_no_Zeros", ".rds")

out_path <-  paste0(here("Output/Spatial/GAM"), "/","GAM", "_" , 
                    "hs_no_Zeros",  "/")

if(!dir.exists(out_path)) dir.create(out_path)
```

#### Data
```{r}
data <- readRDS(here(data_path))

site.by.species <- data$site.by.species
  
site.by.env <- data$site.by.env

site.by.xy <- data$site.by.xy


```


#### Environmental variable, easting, northing and richness Pearson and Spearman correlations
```{r}
site.by.env.and.richness <- cbind(site.by.xy) %>%
  cbind(site.by.env, rowSums(site.by.species)) %>% 
  rename(species.richness = 'rowSums(site.by.species)')
  

```



#GAMS

#### Compare GAMs with different families
```{r}
# Gaussian
gam_gaussian <- gam(species.richness ~ s(mean.ann.temp) + s(log10.mean.ann.rain) + 
                s(topographic.wetness) + s(ph) + s(total.n) + s(tree.density) + 
                s(log10.pesticide.risk) + s(log10.humans),  
                data = site.by.env.and.richness, method= "REML")


gam_tweedie1.01 <- update(gam_gaussian, family = Tweedie(p = 1.01))

gam_tweedie1.1 <- update(gam_gaussian, family = Tweedie(p = 1.1))

gam_tweedie1.2 <- update(gam_gaussian, family = Tweedie(p = 1.2))

gam_tweedie1.3 <- update(gam_gaussian, family = Tweedie(p = 1.3))

gam_tweedie1.4 <- update(gam_gaussian, family = Tweedie(p = 1.4))

gam_tweedie1.5 <- update(gam_gaussian, family = Tweedie(p = 1.5))

gam_tweedie1.6 <- update(gam_gaussian, family = Tweedie(p = 1.6))

gam_tweedie1.7 <- update(gam_gaussian, family = Tweedie(p = 1.7))

gam_tweedie1.8 <- update(gam_gaussian, family = Tweedie(p = 1.8))

gam_tweedie1.9 <- update(gam_gaussian, family = Tweedie(p = 1.9))

gam_tweedie2 <- update(gam_gaussian, family = Tweedie(p = 2))



```

```{r}
gam_tweedies <-list (gam_tweedie1.01, gam_tweedie1.1, gam_tweedie1.2, gam_tweedie1.3, gam_tweedie1.4, gam_tweedie1.5, gam_tweedie1.6, gam_tweedie1.7, gam_tweedie1.8, gam_tweedie1.9, gam_tweedie2)

aic_table <- AIC(gam_tweedie1.01, gam_tweedie1.1, gam_tweedie1.2, gam_tweedie1.3, gam_tweedie1.4, gam_tweedie1.5, gam_tweedie1.6, gam_tweedie1.7, gam_tweedie1.8, gam_tweedie1.9, gam_tweedie2)

kable(aic_table, digits = 2, align = "l")
```












