---
title: "R Notebook"
output: html_notebook
---



#### File Paths
```{r}



# Need all_species data and the best gam for this to further explore residuals
# data_path <- paste0("./Data/Processed_Data/Spatial/all_species.rds/")
# 
# out_path <-  paste0(here("Output/Spatial/GAM/"))
# 
# if(!dir.exists(out_path)) dir.create(out_path)
```


# Add residuals to xy, and env variables to check patterns
```{r}
residuals <- resid(gam_best)
xy.res <- cbind(site.by.xy, residuals)

env.and.res <- cbind(site.by.env.and.richness, residuals)
```


```{r}
pairs(env.and.res[,c(1, 2, 3, 12)])
pairs(env.and.res[, c(4, 5, 6, 12)])
pairs(env.and.res[, c(7, 8, 9, 12)])
pairs(env.and.res[, c(10, 11, 12)])
```
##### Residual plots show a group of observations with low observed species richness but high predicted species richness

```{r}
plot(residuals ~ mean.ann.temp, data = env.and.res)
plot(residuals ~ mean.ann.temp, data = env.and.res, xlim = c(14, 16.1), ylim = c(-22, -14))

plot(residuals ~ species.richness, data = env.and.res, xlim = c(1, 35), ylim = c(-23, 14))

check.res <-filter(env.and.res, residuals < -14, mean.ann.temp > 14)

plot(residuals ~ species.richness, data = check.res, xlim = c(1, 35), ylim = c(-23, 14))
```

#### Look at geographic pattern in residuals
```{r}
coordinates(env.and.res) <- c("x","y")

crs.geo <- CRS("+init=epsg:27700")  # looks up BNG crs
proj4string(env.and.res) <- crs.geo  # define projection system of our data

coordinates(check.res) <- c("x","y")
proj4string(check.res) <- crs.geo  # define projection system of our data


bubble(env.and.res, "residuals", col = c("black","grey"),
       main = "Residuals", xlab = "X-coordinates", ylab = "Y-coordinates")


bubble(check.res, "residuals", col = c("black","grey"),
       main = "Residuals", xlab = "X-coordinates", ylab = "Y-coordinates")
```


#### Plot Sites
```{r }

basemap <-tm_shape(gb) +
  tm_borders()

pointsmap <- basemap +
tm_shape(env.and.res) +
  tm_symbols(size = 0.25, col = "residuals", midpoint = NA)

print(pointsmap)

checkmap <- basemap +
tm_shape(check.res) +
  tm_symbols(size = 0.25, col = "residuals", midpoint = NA)

print(checkmap)
```

#### Check the influence of outliers on the model
```{r}
data.reduced <- as.data.frame(env.and.res)
data.reduced <- data.reduced[ !(data.reduced$residuals < -14 & data.reduced$mean.ann.temp > 14), ]

gam_without_outliers<- update(gam_best,  data = data.reduced)

summary(gam_without_outliers)
par(mfrow = c(2, 2))
gam.check(gam_without_outliers)
my.plot.gam(gam_without_outliers)

```

