---
title: "R Notebook"
output: html_notebook
---

# This makes Figure 3. Update from GAM_plot_test!

```{r}
here::i_am("Scripts/Rmd_Scripts/process_GAMMS_single.Rmd")
library(tidyverse)
library(mgcv)
library(mgcViz)
library(ggpubr)
library(here)
library(conflicted)
conflicts_prefer(dplyr::filter)
conflicts_prefer(dplyr::select)
```


# load gamm objects
```{r}
# they are in this order: ("gamm_corGaus", "gamm_corExp", "gamm_corLin",
#"gamm_corRatio", "gamm_corSpher")

as_mods <- readRDS(here("./Output/Spatial/GAM/GAMM_all_species/gamm_cor_struct_compare_reduced_mod.rds/"))
as_gamm <- as_mods[[2]]

wc_mods <- readRDS(here("./Output/Spatial/GAM/GAMM_wc/gamm_cor_struct_compare_reduced_mod.rds/"))
wc_gamm <- wc_mods[[2]]

hs_mods <- readRDS(here("./Output/Spatial/GAM/GAMM_hs/gamm_cor_struct_compare_reduced_mod.rds/"))
hs_gamm <- hs_mods[[2]]
```

```{r}
out_path <-  here("Output/Spatial/GAM/GAMM_fig//")
if(!dir.exists(out_path)) dir.create(out_path)
```


```{r}

as_viz <-  getViz(as_gamm$gam)
as_plots <- plot(as_viz, allTerms = TRUE) + 
  l_fitLine(colour = "red") + 
  l_rug(mapping = aes(x=x), alpha = 0.8) +
  l_ciLine(mul = 1.96, colour = "blue", linetype = 2) + 
  l_points(shape = 19, size = 1, alpha = 0.1) + 
  theme_classic()
print(as_plots, pages = 1)

wc_viz <-  getViz(wc_gamm$gam)
wc_plots <- plot(wc_viz, allTerms = TRUE) + 
  l_fitLine(colour = "red") + 
  l_rug(mapping = aes(x=x), alpha = 0.8) +
  l_ciLine(mul = 1.96, colour = "blue", linetype = 2) + 
  l_points(shape = 19, size = 1, alpha = 0.1) + 
  theme_classic()

print(wc_plots, pages = 1)

hs_viz <-  getViz(hs_gamm$gam)
hs_plots <- plot(hs_viz, allTerms = TRUE) + 
  l_fitLine(colour = "red") + 
  l_rug(mapping = aes(x=x), alpha = 0.8) +
  l_ciLine(mul = 1.96, colour = "blue", linetype = 2) + 
  l_points(shape = 19, size = 1, alpha = 0.1) + 
  theme_classic()
print(hs_plots, pages = 1)


```

# plot with points and rug, doesn't look so good when panels are small
```{r}
# p1 <- plot(sm(as_viz, 1)) +
#   ylab(NULL) +
#   l_fitLine(colour = "red") +
#   l_rug(mapping = aes(x=x), alpha = 0.8) +
#   l_ciLine(mul = 1.96, colour = "blue", linetype = 2) +
#   l_points(shape = 19, size = 1, alpha = 0.1) +
#   theme_classic() +
#   theme(axis.title.x = element_text(size = 7),
#         axis.text = element_text(size = 4))
```

```{r}
# create 
p1a <- plot(sm(as_viz, 1))
p4a <- plot(sm(as_viz, 2))
p7a <- plot(sm(as_viz, 3))
p10a <- plot(sm(as_viz, 4))
p13a <- plot(sm(as_viz, 5))

p2a <- plot(sm(wc_viz, 1))
p5a <- plot(sm(wc_viz, 2))
p8a <- plot(sm(wc_viz, 3))
p11a <- plot(sm(wc_viz, 4))
p14a <- plot(sm(wc_viz, 5))

p3a <- plot(sm(hs_viz, 1))
p6a <- plot(sm(hs_viz, 2))
p9a <- plot(sm(hs_viz, 3))
p12a <- plot(sm(hs_viz, 4))
p15a <- plot(sm(hs_viz, 5))
```

# for copy and paste (part 1)
```{r}
# p1 <- p1a
# p2 <- p2a
# p3 <- p3a
# p4 <- p4a
# p5 <- p5a
#
# p6 <- p6a
# p7 <- p7a
# p8 <- p8a
# p9 <- p1a
# p10 <- p10a
#
# p11 <- p11a
# p12 <- p12a
# p13 <- p13a
# p14 <- p14a
# p15 <- p15a

```


# Experiment on one plot

```{r}
p1a <- plot(sm(as_viz, 1))

p1 <- p1a +
  ylab("") +
  xlab("") +
  l_fitLine(colour = "red") +
  l_ciLine(mul = 1.96, colour = "blue", linetype = 2) +
  theme_classic() +
  theme(axis.title = element_text(size = 5),
        axis.text = element_text(size = 4)) +
  annotation_custom(grid::textGrob("A", 0.2, 0.95, gp = grid::gpar(fontsize = 7)))
p1
```

# part 2 for copy and paste
```{r}
 # +
 #  ylab("") +
 #  xlab("") +
 #  l_fitLine(colour = "red") +
 #  l_ciLine(mul = 1.96, colour = "blue", linetype = 2) +
 #  theme_classic() +
 #  theme(axis.title = element_text(size = 5),
 #        axis.text = element_text(size = 4)) +
 #  annotation_custom(grid::textGrob("", 0.2, 0.95, gp = grid::gpar(fontsize = 7)))


```
```{r}

```

##### Steps to make this: 1) paste part 1 and uncomment, 2) paste part 2, 3) insert letter annotations and  axis labels (y for plot 7, x for plots 2,5,8,11,14)

```{r}
p1 <- p1a +
  ylab("") +
  xlab("") +
  l_fitLine(colour = "red") +
  l_ciLine(mul = 1.96, colour = "blue", linetype = 2) +
  theme_classic() +
  theme(axis.title = element_text(size = 5),
        axis.text = element_text(size = 4)) +
  annotation_custom(grid::textGrob("A", 0.2, 0.95, gp = grid::gpar(fontsize = 7)))
p2 <- p2a +
  ylab("") +
  xlab("Temperature") +
  l_fitLine(colour = "red") +
  l_ciLine(mul = 1.96, colour = "blue", linetype = 2) +
  theme_classic() +
  theme(axis.title = element_text(size = 5),
        axis.text = element_text(size = 4)) +
  annotation_custom(grid::textGrob("B", 0.2, 0.95, gp = grid::gpar(fontsize = 7)))
p3 <- p3a +
  ylab("") +
  xlab("") +
  l_fitLine(colour = "red") +
  l_ciLine(mul = 1.96, colour = "blue", linetype = 2) +
  theme_classic() +
  theme(axis.title = element_text(size = 5),
        axis.text = element_text(size = 4)) +
  annotation_custom(grid::textGrob("C", 0.2, 0.95, gp = grid::gpar(fontsize = 7)))
p4 <- p4a +
  ylab("") +
  xlab("") +
  l_fitLine(colour = "red") +
  l_ciLine(mul = 1.96, colour = "blue", linetype = 2) +
  theme_classic() +
  theme(axis.title = element_text(size = 5),
        axis.text = element_text(size = 4)) +
  annotation_custom(grid::textGrob("D", 0.2, 0.95, gp = grid::gpar(fontsize = 7)))
p5 <- p5a +
  ylab("") +
  xlab("Top. Wet.") +
  l_fitLine(colour = "red") +
  l_ciLine(mul = 1.96, colour = "blue", linetype = 2) +
  theme_classic() +
  theme(axis.title = element_text(size = 5),
        axis.text = element_text(size = 4)) +
  annotation_custom(grid::textGrob("E", 0.2, 0.95, gp = grid::gpar(fontsize = 7)))

p6 <- p6a +
  ylab("") +
  xlab("") +
  l_fitLine(colour = "red") +
  l_ciLine(mul = 1.96, colour = "blue", linetype = 2) +
  theme_classic() +
  theme(axis.title = element_text(size = 5),
        axis.text = element_text(size = 4)) +
  annotation_custom(grid::textGrob("F", 0.2, 0.95, gp = grid::gpar(fontsize = 7)))
p7 <- p7a +
  ylab("Species Richness (stdized)") +
  xlab("") +
  l_fitLine(colour = "red") +
  l_ciLine(mul = 1.96, colour = "blue", linetype = 2) +
  theme_classic() +
  theme(axis.title = element_text(size = 5),
        axis.text = element_text(size = 4)) +
  annotation_custom(grid::textGrob("G", 0.2, 0.95, gp = grid::gpar(fontsize = 7)))
p8 <- p8a +
  ylab("") +
  xlab("pH") +
  l_fitLine(colour = "red") +
  l_ciLine(mul = 1.96, colour = "blue", linetype = 2) +
  theme_classic() +
  theme(axis.title = element_text(size = 5),
        axis.text = element_text(size = 4)) +
  annotation_custom(grid::textGrob("H", 0.2, 0.95, gp = grid::gpar(fontsize = 7)))
p9 <- p1a +
  ylab("") +
  xlab("") +
  l_fitLine(colour = "red") +
  l_ciLine(mul = 1.96, colour = "blue", linetype = 2) +
  theme_classic() +
  theme(axis.title = element_text(size = 5),
        axis.text = element_text(size = 4)) +
  annotation_custom(grid::textGrob("I", 0.2, 0.95, gp = grid::gpar(fontsize = 7)))
p10 <- p10a +
  ylab("") +
  xlab("") +
  l_fitLine(colour = "red") +
  l_ciLine(mul = 1.96, colour = "blue", linetype = 2) +
  theme_classic() +
  theme(axis.title = element_text(size = 5),
        axis.text = element_text(size = 4)) +
  annotation_custom(grid::textGrob("J", 0.2, 0.95, gp = grid::gpar(fontsize = 7)))

p11 <- p11a +
  ylab("") +
  xlab("Nitro. Dep.") +
  l_fitLine(colour = "red") +
  l_ciLine(mul = 1.96, colour = "blue", linetype = 2) +
  theme_classic() +
  theme(axis.title = element_text(size = 5),
        axis.text = element_text(size = 4)) +
  annotation_custom(grid::textGrob("K", 0.2, 0.95, gp = grid::gpar(fontsize = 7)))
p12 <- p12a +
  ylab("") +
  xlab("") +
  l_fitLine(colour = "red") +
  l_ciLine(mul = 1.96, colour = "blue", linetype = 2) +
  theme_classic() +
  theme(axis.title = element_text(size = 5),
        axis.text = element_text(size = 4)) +
  annotation_custom(grid::textGrob("L", 0.2, 0.95, gp = grid::gpar(fontsize = 7)))
p13 <- p13a +
  ylab("") +
  xlab("") +
  l_fitLine(colour = "red") +
  l_ciLine(mul = 1.96, colour = "blue", linetype = 2) +
  theme_classic() +
  theme(axis.title = element_text(size = 5),
        axis.text = element_text(size = 4)) +
  annotation_custom(grid::textGrob("M", 0.2, 0.95, gp = grid::gpar(fontsize = 7)))
p14 <- p14a +
  ylab("") +
  xlab("Log Humans") +
  l_fitLine(colour = "red") +
  l_ciLine(mul = 1.96, colour = "blue", linetype = 2) +
  theme_classic() +
  theme(axis.title = element_text(size = 5),
        axis.text = element_text(size = 4)) +
  annotation_custom(grid::textGrob("N", 0.2, 0.95, gp = grid::gpar(fontsize = 7)))
p15 <- p15a +
  ylab("") +
  xlab("") +
  l_fitLine(colour = "red") +
  l_ciLine(mul = 1.96, colour = "blue", linetype = 2) +
  theme_classic() +
  theme(axis.title = element_text(size = 5),
        axis.text = element_text(size = 4)) +
  annotation_custom(grid::textGrob("O", 0.2, 0.95, gp = grid::gpar(fontsize = 7)))
```



```{r}

gridPrint(p1, p2, p3, 
          p4, p5, p6,
          p7, p8, p9,
          p10, p11, p12,
          p13, p14, p15,
          respect=TRUE,
          ncol = 3)

png(file = paste0(out_path, "gam_multiplot.png"), pointsize=10, width=960, height=1400, res=300)
 
 gridPrint(p1, p2, p3, 
          p4, p5, p6,
          p7, p8, p9,
          p10, p11, p12,
          p13, p14, p15,
          respect=TRUE,
          ncol = 3)

 dev.off() 
```

