---
title: "R Notebook"
output: html_notebook
---


#### Packages
```{r}
here::i_am("Scripts/Rmd_Scripts/GAMM_analyses_2.Rmd")
library(tidyverse)
library(mgcv)
library(knitr)
library(tictoc)
library(here)
library(conflicted)
conflicts_prefer(dplyr::filter)
conflicts_prefer(dplyr::select)
conflicts_prefer(knitrProgressBar::progress_estimated)
# there is a same-named function in dplyr, check it out
```
#### Functions
```{r}
# From https://stackoverflow.com/questions/71252509/is-there-a-way-to-get-progress-information-whan-a-chunk-is-running-in-rmarkdown

slow_function <- function(i, .pb=NULL) {  
  update_progress(.pb)  
  Sys.sleep(0.5)  
  i  
}
# create an R6 progress object for
# the number of loops/iterations in the target chunk
```

#### File Paths
```{r}
out_path <-  here("Output/Spatial/GAM")
if(!dir.exists(out_path)) dir.create(out_path)
```

#### Datasets for gamms
```{r}

all_species <- readRDS(here("./Data/Processed_Data/Spatial/all_species.rds"))
wc <- readRDS(here("./Data/Processed_Data/Spatial/wc.rds"))
hs <- readRDS(here("./Data/Processed_Data/Spatial/hs.rds"))
hs_no_zeros <- readRDS(here("./Data/Processed_Data/Spatial/hs_no_zeros.rds"))

# get all datasets in a list
datasets <- list(all_species, wc, hs, hs_no_zeros)
names(datasets) <- c("all_species", "wc", "hs", "hs_no_zeros")
```


#### for each dataset, prepare data for gamm input, remove transects that are duplicates for x and y coordinates (keep first one)
```{r}
for (i in 1: length(datasets)){ 
print(names(datasets[i]))
  
data <- datasets[[i]]

site.by.species <- data$site.by.species
site.by.env <- data$site.by.env
site.by.xy <- data$site.by.xy
sites <- data$sites

# assemble xy, environmental vars and richness for analysis
site.by.env.xy.richness <- cbind(site.by.env, rowSums(site.by.species)) %>%
  cbind(site.by.xy) %>%
rename(species.richness = 'rowSums(site.by.species)')

#inspect duplicates to see how they arise
dup_xy <- sites %>%
  mutate(xy = paste(x,y)) %>%
group_by(xy) %>% 
  filter(n() > 1)

print(kable(dup_xy, caption = names(datasets[i])))
  
#remove duplicates for rows with the same x and y coordinates
gamm_input <- site.by.env.xy.richness %>%
  mutate(xy = paste(x,y)) %>%
  distinct(xy, .keep_all = TRUE)

hist(gamm_input$species.richness, main = names(datasets[i]))

# add the input for the gamm to each dataset
gamm_input <- list(gamm_input)
names(gamm_input) <- "gamm_input"
datasets[[i]] <- c(datasets[[i]], gamm_input)
}
```
#### Specify  correlation structures
```{r}
corStructs <- list(corGaus(form = ~x+y, nugget = TRUE), corExp(form = ~x+y, nugget = TRUE), corLin(form = ~x+y, nugget = TRUE), corRatio(form = ~x+y, nugget = TRUE), corSpher(form = ~x+y, nugget = TRUE) )
```

### All Species
```{r}

#note gamm4 does not take correlation structure

#did not converge. First reduced k to 5 for all terms, which should be fine 
# k = 5 does not make a big difference compared to default k = 9 in gams

# another way may be, from ?gamm, "In the event of lme convergence failures, consider modifying options(mgcv.vc.logrange): reducing it helps to remove indefiniteness in the likelihood, if that is the problem, but too large a reduction can force over or undersmoothing."

tic()

gamm_as <- gamm(
  species.richness ~ s(mean.ann.temp, k = 5) + s(log10.mean.ann.rain, k = 5) + 
  s(topographic.wetness, k = 5) + s(ph, k = 5) + s(total.n, k = 5) + s(tree.density, k = 5) + 
  s(log10.pesticide.risk, k = 5) + s(log10.humans, k = 5), 
  method = "REML", 
  correlation = corStructs[[2]], #corExp
  data = datasets$all_species$gamm_input)


filedir <- paste0(here(out_path), "/GAMM_all_species")
if(!dir.exists(filedir)) dir.create(filedir)
filepath <- paste0(filedir, "/gamm_all_species_exp_gaus2.rds")
filepath
write_rds(gamm_as, 
          file = filepath)

toc()

```


### Wider Countryside

```{r}
try(gamm_wc <- gamm(
  species.richness ~ s(mean.ann.temp, k = 5) + s(log10.mean.ann.rain, k = 5) + 
  s(topographic.wetness, k = 5) + s(ph, k = 5) + s(total.n, k = 5) + s(tree.density, k = 5) + 
  s(log10.pesticide.risk, k = 5) + s(log10.humans, k = 5), 
  method = "REML", 
  correlation = corStructs[[2]], #corExp
  data = datasets$wc$gamm_input))

filedir <- paste0(here(out_path), "/GAMM_wc")
if(!dir.exists(filedir)) dir.create(filedir)
filepath <- paste0(filedir, "/gamm_wc_exp_gaus2.rds")
filepath
try(write_rds(gamm_wc , 
          file = filepath))
```


### Habitat Specialists

```{r}
# family = nb() not appropriate in gamm, gives warning
try(gamm_hs <- gamm(
  species.richness ~ s(mean.ann.temp, k = 5) + s(log10.mean.ann.rain, k = 5) + 
  s(topographic.wetness, k = 5) + s(ph, k = 5) + s(total.n, k = 5) + s(tree.density, k = 5) + 
  s(log10.pesticide.risk, k = 5) + s(log10.humans, k = 5), 
  method = "REML", 
  correlation = corStructs[[3]], #corLin
  data = datasets$hs$gamm_input,
  family = negbin(theta = 4.663)))#value from gam


filedir <- paste0(here(out_path), "/GAMM_hs")
if(!dir.exists(filedir)) dir.create(filedir)
filepath <- paste0(filedir, "/gamm2_hs_lin_nb.rds")
filepath
try(write_rds(gamm_hs , 
          file = filepath))
```
