---
title: "R Notebook"
output: html_notebook
---

```{r}
here::i_am("Scripts/Rmd_Scripts/Gamm_multipanel_fig.Rmd")
library(tidyverse)
library(ggpubr)
library(mgcv)
library(mgcViz)
library(grid)
library(gridExtra)
library(here)
library(conflicted)

conflicts_prefer(dplyr::filter)
conflicts_prefer(dplyr::select)
```
```{r}
out_path <-  here("Output/Spatial/msgdms/msgdm_multipanel//")
if(!dir.exists(out_path)) dir.create(out_path)

```

# load gamm objects
```{r}
my_panels <- list()

my_panels[1:9] <- readRDS(here("./Output/Spatial/msgdms/all_species_Simpson_4//figs_tables//msgdm_single_splines.rds"))

#my_panels[10:27]<- 1:18

my_panels[10:18] <- readRDS(here("./Output/Spatial/msgdms/wc_Simpson_4//figs_tables//msgdm_single_splines.rds"))
my_panels[19:27] <- readRDS(here("./Output/Spatial/msgdms/hs_no_zeros_Simpson_4//figs_tables//msgdm_single_splines.rds"))

names(my_panels) <- paste0("p", c(1, 4, 7, 10, 13, 16, 19, 22, 25, 
                                  2, 5, 8, 11, 14, 17, 20, 23, 26, 
                                  3, 6, 9, 12, 15, 18, 21, 24, 27), "a")

#save originals to avoid having to reload from rds when working
#my_panels1 <- my_panels

#my_panels <- my_panels1 
```





```{r}
# Column headings
top_heads <- c("All", "Generalists", "Specialists")
# Panel labels
panel_letters <- c("A", "D", "G", "J", "M", "P", "S", "V", "Y",
                   "B", "E", "H", "K", "N", "Q", "T", "W", "Z",
                   "C", "F", "I", "L", "O", "R", "U", "X", "AA")
# x-axis legends
x_labels <- c("Temperature", "Log Prec.", "Top. Wet.", "pH", "Nit. Dep.", "Tree Dens.", "Log Pestic.", "Log Humans", "Geog. Dist.")


for (i in 1:27){
  # for each panel adjust appearance as follows
  p_i <-  my_panels[[i]]
  # Remove x axis legend for panels not in middle column and rename legend for panels that are in the middle column
  if (!is.element(i, 10:18)) {
    p_i <-  p_i + 
      xlab("")
    } else {
    p_i <- p_i + 
      xlab(x_labels[i - 9])    
      }
  # only include y axis legend for the middle left panel
  if (i ==5) {
    p_i <-  p_i + 
      ylab("Turnover") 
  }
  # remove x axis labels except for bottom row of panels
  if (!is.element(i, c(9, 18, 27))) {
    p_i <-  p_i + 
  theme(axis.text.x=element_blank())
  }
  # add panel labels to each panel
  p_i <- p_i +
    annotation_custom(grid::textGrob(panel_letters[i], 0.15, 0.9, gp = grid::gpar(fontsize = 6))) 
  my_panels[[i]] <- p_i
}

```

```{r}
start_index <- c(1, 10, 19)
my_index <- start_index
for (i in 1:8){
  my_index <- c(my_index, start_index +i)
}
my_panels2 <- list()

for (i in 1:27){
  my_panels2[[i]]<- my_panels[[my_index[i]]]
}
```


```{r}
#list2env(my_panels, envir = .GlobalEnv)
#rm(my_panels)
```
```{r}
#inspect
 # gridPrint(p1a, p2a, p3a, 
 #          p4a, p5a, p6a,
 #          p7a, p8a, p9a,
 #          p10a, p11a, p12a,
 #          p13a, p14a, p15a,
 #          p16a, p17a, p18a,
 #         # p19a, p20a, p21a,
 #         # p22a, p23a, p24a,
 #          #p25a, p26a, p27a,
 #          respect=TRUE,
 #          ncol = 3)
```
```{r}
nr <- 9
nc <- 3

combine <- rbind(tableGrob(t(top_heads), theme = ttheme_minimal(), rows = ""), 
                 cbind(tableGrob(rep(" ",nr), theme = ttheme_minimal()), # I couldn't work out how not to have row headings so made them a space 
                       arrangeGrob(grobs = my_panels2, ncol = 3),  size = "last"), size = "last")




#check = arrangeGrob(grobs = my_panels2, ncol = 3)

grid.newpage()
grid.draw(combine)



```
```{r}
png(file = paste0(out_path, "msgdm_multiplot.png"), pointsize=10, width=960, height=2000, res=300)
grid.newpage()
grid.draw(combine)
dev.off()
```


```{r}
pl <- replicate(12, ggplot(), FALSE)

#N <- length(pl)
nr <- 4
nc <- 3


combine <- rbind(tableGrob(t(c(letters[1:nc])), theme = ttheme_minimal(), rows = ""), 
                 cbind(tableGrob(LETTERS[1:nr], theme = ttheme_minimal()), 
                       arrangeGrob(grobs = pl),  size = "last"), size = "last")
grid.newpage()
grid.draw(combine)
```


