---
title: "R Notebook"
output: html_notebook
---

This is to randomise butterfly data for sharing with gabi

#### set up
```{r}
here::i_am("Scripts//Rmd_Scripts//Randomise_butterflies.Rmd")

library(conflicted)

library(tidyverse)

library(here)

library(tictoc)

conflicts_prefer(dplyr::filter)
conflicts_prefer(dplyr::mutate)
conflicts_prefer(dplyr::select)
```


#### Data
```{r}
tic()
# UKBMS records data extracted by David Roy on 10th March 2023
records <- read_csv(here("./Data/CSV_Data/ukbms_Rogers_10-3-23.csv"))

# UKBMS site data extracted by David Roy on 10th March 2023 with some preprocessing using excel (see below)
sites <- read_csv(here("./Data/CSV_Data/ukbms_Rogers_sites_10-3-23_to_correct.csv"))

# UKBMS site data provided by Rob Cooke. This includes type of survey for each site
sites.more.info <- read_csv(here("./Data/CSV_Data/ukbmsSiteLocationData1976-2019.csv"))

# UKBMS species data extracted by David Roy on 10th March 2023
species <- read_csv(here("./Data/CSV_Data/ukbms_Rogers_species_10-3-23.csv"))

# Basemap with outlying islands
GB <- readRDS(here("./Data./Maps./gb_multipolygon_incl_ork_shet_simplified.rds"))

# Basemap without outlying islands
GB_simpl <- readRDS(here("./Data./Maps./gb_multipolygon_simplified.rds"))
```


```{r}
# a random selection of 100000 rows

set.seed(1)
samp_rows <- sample(1:nrow(records), 100000)
rand_rec <- records[samp_rows, ]

head(rand_rec)

#shuffle SITE AND YEAR
set.seed(1)
rand_rec$SITE <- sample(rand_rec$SITE, 100000)
set.seed(1)
rand_rec$YEAR <- sample(rand_rec$YEAR, 100000)

head(rand_rec)
```
```{r}
write_csv(rand_rec, here("./Data/Processed_Data/ukbms_randomised.csv"))
```

