---
title: "Render Analysis Reports"
output: html_notebook
---
 
# this calls the markdowns and generate reports with specified parameters

## setup
```{r}
here::i_am("Scripts/Rmd_Scripts/run_zeta_msgdm.Rmd")

library(tidyverse)

library(zetadiv)

library(rmarkdown)

library(tictoc)

library(here)

library(conflicted)

conflicts_prefer(dplyr::select)
```


##  Load functions
```{r}
source(here("./Scripts/R_scripts/get_k_fold_performance.R"))

source(here("./Scripts/R_scripts/Zeta.order.mc.sam.R"))

source(here("./Scripts/R_scripts/get_validation_different_seeds_and_samps.R"))


# https://bookdown.org/yihui/rmarkdown/params-knit.html#knit-with-custom-parameters


render_report = function(analysis_script, params_list) {
  out_path <- if (analysis_script == "Zeta_declines_decays_analyses.Rmd"){
                    paste0(here("Output/Spatial/zeta_declines_decays"), "/", params_list$dataset,  "/")
                } else if(analysis_script == "Zeta_msgdm_analyses.Rmd") {
                    paste0(here("Output/Spatial/msgdms/"), "/", params_list$dataset, "_" , params_list$normalize_msgdm)
                } else if(analysis_script == "GAM_compare_family_analyses.Rmd") {
                      paste0(here("Output/Spatial/GAM"), "/","GAM", "_" , params_list$dataset,  "/")  
                } else if(analysis_script == "GAM_compare_spline_analyses.Rmd") {
                      paste0(here("Output/Spatial/GAM"), "/","GAM", "_" , params_list$dataset,  "/") 
                } else if(analysis_script == "process_GAMM_analyses.Rmd"){  
                      paste0(here("Output/Spatial/GAM"), "/", params_list$analysis, "/")
                } else if(analysis_script == "process_GAMMS_single.Rmd"){  
                      paste0(here("Output/Spatial/GAM/GAMM_"), "/", params_list$dataset, "/")
                } else if(analysis_script == "process_msgdm_results.Rmd"){  
                      paste0(here("Output/Spatial/msgdms"), "/", 
                      params_list$dataset, "_" , params_list$normalize_msgdm, "/", 
                      "figs_tables/")
                }
if(!dir.exists(out_path)) dir.create(out_path, recursive = TRUE)
  rmarkdown::render(input = analysis_script,
                    output_dir = out_path,
                    params = params_list)
}
```




## Zeta declines and decays
```{r}
tic()
render_report(analysis_script = "Zeta_declines_decays_analyses.Rmd", list(dataset = "all_species", sam_ddecay = 10000, orders_ddecay = 2:100))
toc()
tic()
render_report(analysis_script = "Zeta_declines_decays_analyses.Rmd", list(dataset = "wc", sam_ddecay = 10000, orders_ddecay = 2:100))
toc()
#render_report(analysis_script = "Zeta_declines_decays_analyses.Rmd", list(dataset = "wc_no_zeros", sam_ddecay = 10000, orders_ddecay = 2:100))
tic()
render_report(analysis_script = "Zeta_declines_decays_analyses.Rmd", list(dataset = "hs", sam_ddecay = 10000, orders_ddecay = 2:8)) # Computational issues at higher orders
toc()
tic()
render_report(analysis_script = "Zeta_declines_decays_analyses.Rmd", list(dataset = "hs_no_zeros", sam_ddecay = 10000, orders_ddecay = 2:10)) # Computational issues at higher orders
toc()
```

#### GAMS comparing different distribution families

```{r}
render_report(analysis_script = "GAM_compare_family_analyses.Rmd", list(dataset = "all_species"))
```

```{r}
render_report(analysis_script = "GAM_compare_family_analyses.Rmd", list(dataset = "wc"))
```

```{r}
#render_report(analysis_script = "GAM_compare_family_analyses.Rmd", list(dataset = "hs_no_zeros"))
```


```{r}
render_report(analysis_script = "GAM_compare_family_analyses.Rmd", list(dataset = "hs"))
```


#### GAMMS
Note, GAMMS conducted in GAMM_analyses.Rmd notebook


```{r}
render_report(analysis_script = "process_GAMM_analyses.Rmd", 
              list(gamm_path = "Output/Spatial/GAM/GAMM_all_species//", 
                   analysis = "GAMM_all_species"))
```
#### wider countryside
```{r}
render_report(analysis_script = "process_GAMM_analyses.Rmd", 
              list(gamm_path = "Output/Spatial/GAM/GAMM_wc//", 
                   analysis = "GAMM_wc"))
```

#### Habitat Specialists
```{r}
render_report(analysis_script = "process_GAMM_analyses.Rmd", 
              list(gamm_path = "Output/Spatial/GAM/GAMM_hs//", 
                   analysis = "GAMM_hs"))
```


### Single GAMMS
```{r}
render_report(analysis_script = "process_GAMMS_single.Rmd", 
              list(gamm_file = "gamm_all_species_exp_gaus2.rds", 
                   dataset = "all_species"))
```


#### WC
```{r}
render_report(analysis_script = "process_GAMMS_single.Rmd", 
              list(gamm_file = "gamm_wc_exp_gaus2.rds", 
                   dataset = "wc"))
```



#### HS
```{r}
render_report(analysis_script = "process_GAMMS_single.Rmd", 
              list(gamm_file = "gamm2_hs_lin_nb.rds", 
                   dataset = "hs"))
```



## MSGDMs
```{r}
tic()
render_report(analysis_script = "Zeta_msgdm_analyses.Rmd", list(dataset = "all_species",
              orders_msgdm =  c(2, 3, 4, 6, 10, 15, 20, 50), sam_msgdm = 50000, normalize_msgdm = "Simpson"))
toc()

tic()
render_report(analysis_script = "Zeta_msgdm_analyses.Rmd", list(dataset = "wc",  
              orders_msgdm =  c(2, 3, 4, 6, 10, 15, 20, 50), sam_msgdm = 50000, normalize_msgdm = "Simpson"))
toc()

tic()
render_report(analysis_script = "Zeta_msgdm_analyses.Rmd", list(dataset = "hs_no_zeros",  
              orders_msgdm =  c(2, 3, 4, 5, 6), sam_msgdm = 50000, normalize_msgdm = "Simpson"))
toc()

tic()
render_report(analysis_script = "Zeta_msgdm_analyses.Rmd", list(dataset = "all_species",
              orders_msgdm =  c(2, 3, 4, 6, 10, 15, 20, 50), sam_msgdm = 50000, normalize_msgdm = "Sorensen"))
toc()


tic()
render_report(analysis_script = "Zeta_msgdm_analyses.Rmd", list(dataset = "wc",  
              orders_msgdm =  c(2, 3, 4, 6, 10, 15, 20, 50), sam_msgdm = 50000, normalize_msgdm = "Sorensen"))
toc()



tic()
render_report(analysis_script = "Zeta_msgdm_analyses.Rmd", list(dataset = "hs_no_zeros",  
              orders_msgdm =  c(2, 3, 4, 5, 6), sam_msgdm = 50000, normalize_msgdm = "Sorensen"))
toc()

```

#### Generate tables and figures for msgdms
```{r}
render_report(analysis_script = "process_msgdm_results.Rmd", 
              list(dataset = "all_species", normalize_msgdm = "Simpson",
                   orders_msgdm =  c(2, 3, 4, 6, 10, 15, 20, 50)))

render_report(analysis_script = "process_msgdm_results.Rmd", 
              list(dataset = "wc", normalize_msgdm = "Simpson",
                   orders_msgdm =  c(2, 3, 4, 6, 10, 15, 20, 50)))

render_report(analysis_script = "process_msgdm_results.Rmd", 
              list(dataset = "hs_no_zeros", normalize_msgdm = "Simpson",
                   orders_msgdm =  c(2, 3, 4, 5, 6)))

render_report(analysis_script = "process_msgdm_results.Rmd", 
              list(dataset = "all_species", normalize_msgdm = "Sorensen",
                   orders_msgdm =  c(2, 3, 4, 6, 10, 15, 20, 50)))

render_report(analysis_script = "process_msgdm_results.Rmd", 
              list(dataset = "wc", normalize_msgdm = "Sorensen",
                   orders_msgdm =  c(2, 3, 4, 6, 10, 15, 20, 50)))

render_report(analysis_script = "process_msgdm_results.Rmd", 
              list(dataset = "hs_no_zeros", normalize_msgdm = "Sorensen",
                   orders_msgdm =  c(2, 3, 4, 5, 6)))

```

