---
title: "Zeta Msgdm Analyses"
output: html_document

params:
  dataset: "all_species"
  sam_msgdm: 100
  orders_msgdm: 
   - 2
   - 3
  normalize_msgdm: "Simpson"
---

"You can also run arbitrary R expressions by prefacing the parameter value with !r"
https://r4ds.had.co.nz/r-markdown.html

```{r}
# You can also run arbitrary R expressions by prefacing the parameter value with !r
# https://r4ds.had.co.nz/r-markdown.html
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#### Packages
```{r}
here::i_am("Scripts/Rmd_Scripts/run_zeta_msgdm.Rmd")

library(tidyverse)
library(zetadiv)
library(here)
library(conflicted)
library(knitr)
library(knitrProgressBar)
library(tictoc)

conflicts_prefer(dplyr::select)
conflicts_prefer(knitrProgressBar::progress_estimated)

# there is a same-named function in dplyr, check it out
```

#### Functions
```{r}
# From https://stackoverflow.com/questions/71252509/is-there-a-way-to-get-progress-information-whan-a-chunk-is-running-in-rmarkdown

slow_function <- function(i, .pb=NULL) {  
  update_progress(.pb)  
  Sys.sleep(0.5)  
  i  
}

# create an R6 progress object for
# the number of loops/iterations in the target chunk
```

#### File Paths
```{r}
data_path <- paste0("./Data/Processed_Data/Spatial/", params$dataset, ".rds")

out_path <-  paste0(here("Output/Spatial/msgdms"), "/", params$dataset, "_" , params$normalize_msgdm, "/")

if(!dir.exists(out_path)) dir.create(out_path, recursive = TRUE)
```

#### Data
```{r}
data <- readRDS(here(data_path))

site.by.species <- data$site.by.species
  
site.by.env <- data$site.by.env

site.by.xy <- data$site.by.xy
```

#### Parameters for this report
```{r}
print(params)
```



#### Environmental variable Pearson and Spearman correlations
```{r}
t1 <- cor(site.by.env)
t2 <- cor(site.by.env, method = "spearman")

print("Pearson correlation")
t1
print("Spearman correlation")
t2
```







```{r}

n_iterations <- length(params$orders_msgdm)
pb <- progress_estimated(n_iterations)

output0 <- list()

for (i in 1:length(params$orders_msgdm)) {
slow_function(i, .pb=pb)
set.seed(1)
my.msgdm <-  Zeta.msgdm(xy = site.by.xy, data.spec = site.by.species, data.env = site.by.env,  order = params$orders_msgdm[[i]], sam = params$sam_msgdm,
  reg.type="ispline", normalize=params$normalize_msgdm, family=binomial(link="log"),cons.inter = -1, glm.init = TRUE) 
output0[[i]] <- my.msgdm
print(paste0("Zeta = ", params$orders_msgdm[i]))
print(Sys.time())

}

names(output0) <- paste0("msgdm.", params$orders_msgdm)


write_rds(output0, file = paste0(here(out_path), "/", params$dataset, "_", params$normalize_msgdm, "_zeta_msgdms.rds"))

```

## MSGDM summaries
```{r}
for (i in 1:length(params$orders_msgdm)) {
print(names(output0[i]))
print(summary(output0[[i]]$model))
}
```

# MSGDM deviance explained
```{r}
for (i in 1:length(params$orders_msgdm)) {
print(names(output0[i]))
print(with(summary(output0[[i]]$model), 1 - deviance/null.deviance))
}
```

### MSGDM i-spline plots
```{r}



for (i in 1:length(params$orders_msgdm)) {
  
##Plot.ispline(msgdm = output0[[i]], data.env = site.by.env, distance = TRUE,  legend = TRUE)
  filepath <- paste0(out_path, "ispline_plot_",params$dataset, "_", params$normalize_msgdm, "_zeta_order", params$orders_msgdm[i], ".png")

#For unknown reasons, over writing is not happening  
unlink(filepath, recursive = FALSE, force = FALSE) #deletes previous version with the same name
    
png(file = filepath)
Plot.ispline(msgdm = output0[[i]], data.env = site.by.env, distance = TRUE,  legend = TRUE)
dev.off()  
  
}

```

#MSGDM deviance partitioning
```{r}
varparts <- list()

for (i in 1:length(params$orders_msgdm)) {
  set.seed(1)
  varparts[[i]] <- Zeta.varpart(msgdm.mod = output0[[i]], method.glm = "glm.fit2", cons.inter = -1) 
}
names(varparts) <- paste0("zeta.vapart.", params$orders_msgdm)

for (i in 1:length(params$orders_msgdm)) {
pie.neg(varparts[[i]][4:7,1], density = c(4, 0, 8, -1),  angle = c(90, 0, 0, 0), labels =  c("distance","undistinguishable","environment","unexplained"), radius = 0.9, main = paste0("Zeta = ", params$orders_msgdm[i]))
  
png(file = paste0(out_path, "msgdm_var_pie_",params$dataset, "_", params$normalize_msgdm, "_zeta_order", params$orders_msgdm[i], ".png"))
pie.neg(varparts[[i]][4:7,1], density = c(4, 0, 8, -1),  angle = c(90, 0, 0, 0), labels =  c("distance","undistinguishable","environment","unexplained"), radius = 0.9, main = paste0("Zeta = ", params$orders_msgdm[i]))
dev.off()  
    
}
```



