---
title: "Zeta Declines and Decays"
output: html_document

params:
  dataset: "all_species"
  sam_ddecay: 100
  orders_ddecay: !r 2:100
  run_decay_analysis: FALSE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Parameterised reports: see https://r4ds.had.co.nz/r-markdown.html
```

#### Packages
```{r}
here::i_am("Scripts/Rmd_Scripts/Zeta_declines_decays_analyses.Rmd")

library(tidyverse)
library(zetadiv)
library(mgcv)
library(here)
library(conflicted)
library(knitr)
library(knitrProgressBar)
library(tictoc)

conflicts_prefer(dplyr::select)
conflicts_prefer(knitrProgressBar::progress_estimated)
```

#### Functions
```{r}
# From https://stackoverflow.com/questions/71252509/is-there-a-way-to-get-progress-information-whan-a-chunk-is-running-in-rmarkdown
# create an R6 progress object for
# the number of loops/iterations in the target chunk
slow_function <- function(i, .pb=NULL) {  
  update_progress(.pb)  
  Sys.sleep(0.5)  
  i  
}
```

#### File Paths
```{r}
data_path <- paste0("./Data/Processed_Data/Spatial/", params$dataset, ".rds")

out_path <-  paste0(here("Output/Spatial/zeta_declines_decays"), "/", params$dataset, "/")

if(!dir.exists(out_path)) dir.create(out_path, recursive = TRUE)
```

#### Data
```{r}
data <- readRDS(here(data_path))

site.by.species <- data$site.by.species
  
site.by.env <- data$site.by.env

site.by.xy <- data$site.by.xy

species <- data$species
```

#### Parameters for this report
```{r}
print(params)
```

## Zeta Declines

### Orders 1:10
```{r}
zd <- Zeta.decline.ex(data.spec = site.by.species, orders = 1:10)
# "Power Law"
summary(zd$zeta.pl)
# Exponential")
summary(zd$zeta.exp)
# "AIC"
# zd$aic has dollar signs in rownames, which messes up resulting table from kable
# therefore I edit the rownames
zd_performance <- zd$aic
rownames(zd_performance) <- c("Exp_to_zeta_10", "PL_to_zeta_10")
zd_performance$R.sq.multi <- c(summary(zd$zeta.exp)$r.squared, 
                              summary(zd$zeta.pl)$r.squared)
zd_performance$R.sq.adj <- c(summary(zd$zeta.exp)$adj.r.squared, 
                              summary(zd$zeta.pl)$adj.r.squared)
kable(zd_performance)

# Keep to add values from below
all_performance <- zd_performance
```

```{r}

png(file = paste0(out_path, params$dataset, "_", "zeta_decline_to_10.png"), pointsize = 6, width=960, height=960, res=300)
par(mfrow = c(2,2))
Plot.zeta.decline(zd, arrange.plots = FALSE)
dev.off()

```

### Orders 1:50
```{r}
zd <- Zeta.decline.ex(data.spec = site.by.species, orders = 1:50)
# "Power Law"
summary(zd$zeta.pl)
# Exponential")
summary(zd$zeta.exp)
# "AIC"
zd_performance <- zd$aic
rownames(zd_performance) <- c("Exp_to_zeta_50", "PL_to_zeta_50")
zd_performance$R.sq.multi <- c(summary(zd$zeta.exp)$r.squared, 
                              summary(zd$zeta.pl)$r.squared)
zd_performance$R.sq.adj <- c(summary(zd$zeta.exp)$adj.r.squared, 
                              summary(zd$zeta.pl)$adj.r.squared)
kable(zd_performance)

all_performance <- rbind(all_performance, zd_performance)

```

```{r}

png(file = paste0(out_path, params$dataset, "_", "zeta_decline_to_50.png"), pointsize = 6, width=960, height=960, res=300)
par(mfrow = c(2,2))
Plot.zeta.decline(zd, arrange.plots = FALSE)
dev.off()

```

### Orders 1:250
```{r}
zd <- Zeta.decline.ex(data.spec = site.by.species, orders = 1:250)
# "Power Law"
summary(zd$zeta.pl)
# Exponential")
summary(zd$zeta.exp)
# "AIC"
zd_performance <- zd$aic
rownames(zd_performance) <- c("Exp_to_zeta_250", "PL_to_zeta_250")
zd_performance$R.sq.multi <- c(summary(zd$zeta.exp)$r.squared, 
                              summary(zd$zeta.pl)$r.squared)
zd_performance$R.sq.adj <- c(summary(zd$zeta.exp)$adj.r.squared, 
                              summary(zd$zeta.pl)$adj.r.squared)
kable(zd_performance)


```

# Below not used in paper but shows that results are qualitatively the same
```{r}
# Finalise a datafram summarising performance of exponential versus power law
# declines
all_performance <- rbind(all_performance, zd_performance)
infocols <- data.frame(rep(c("Exponential", "Power Law"), times = 3))
names(infocols) <- "Regression Fit"
infocols$'Zeta values' <- rep(c("1 to 10", "1 to 50", "1 to 250"), each = 2)
all_performance <- cbind(infocols, all_performance)

# Output the zeta diversity to csv
zeta_div <- data.frame(cbind(zd$zeta.order, zd$zeta.val, zd$zeta.val.sd))
names(zeta_div) <- c("Order", "Value", "SD")
```


```{r}
write_csv(all_performance, file = paste0(out_path, "/", params$dataset, "_",  "zeta_declines_performance.csv"))
kable(all_performance, digits = 3)
```

```{r}

png(file = paste0(out_path, params$dataset, "_", "zeta_decline_to_250.png"), pointsize=10, width=960, height=960, res=300)
par(mfrow = c(2,2))
Plot.zeta.decline(zd, arrange.plots = FALSE)
dev.off()

```
```{r}
write_csv(zeta_div, file = paste0(out_path, params$dataset, "_",  "zeta_decline_exact.csv"))
kable(t(zeta_div), digits = 2)
```




## check nestedness by comparing Sorensen and Simpson Dissimilarity (Cang's code)
```{r}

jac <- vector()
sor <- vector()
sim <- vector()

for(i in 1:1000){
a <- sample(1:nrow(site.by.species),2)  
unio <- sum(ifelse((site.by.species[a[1],] == 1)|(site.by.species[a[2],]==1),1,0))
inter <- sum(site.by.species[a[1],]*site.by.species[a[2],])
minn <- min(sum(site.by.species[a[1],]),sum(site.by.species[a[2],]))
avg <- (sum(site.by.species[a[1],])+sum(site.by.species[a[2],]))/2
jac[i] <- inter/unio
sor[i] <- inter/avg
sim[i] <- inter/minn
}

boxplot(jac,sor,sim)
text("Jaccard","Sorensen","Simpson")

group <- c(rep("Jaccard", 1000), rep("Sorensen", 1000), rep("Simpson", 1000))
Dissimilarity <- as.numeric(c(jac, sor, sim))

boxdata <-data.frame(cbind(group, Dissimilarity))

boxdata$Dissimilarity <- as.numeric(boxdata$Dissimilarity)


boxplot(Dissimilarity ~ group, boxdata,                                
        col = "red",
        xlab = NULL,
        cex.axis = 1)

# save boxplot
png(file = paste0(out_path, "zeta_boxplot.png"), pointsize=8, width=960, height=960, res=300)
boxplot(Dissimilarity ~ group, boxdata,                                
        col = "red",
        xlab = NULL,
        cex.axis = 1)
dev.off()



# compare Sorensen versus Simpson data to test for nestedness
m1 <- lm(Dissimilarity ~ group, boxdata[1001:3000,])

summary(m1)


```
# Save anova table to check nestedness

```{r}
# Obtain data to population caption for anova table

my_dataset <- case_when(params$dataset == "all_species" ~ "All Species",
                        params$dataset == "wc" ~ "Wider Countryside Species",
                        params$dataset == "hs" ~ "Habitat Specialists")

my_rsq <- summary(m1)$r.squared %>%
  signif(2) %>%
  as.character

my_rsq_adj <- summary(m1)$adj.r.squared %>%
  signif(2) %>%
  as.character

my_SE <- summary(m1)$sigma %>%
  signif(2) %>%
  as.character

my_num_df <- (summary(m1)$df[1] - 1)  %>%
  as.character

my_denom_df <-summary(m1)$df[2]  %>%
  as.character


anova_caption <- paste0("Comparison of Simpson and Sorensen dissimilarity for pairs of sites for ", 
                        my_dataset, ". Residual standard error = ",  my_SE, " on ",
                        my_num_df, " and ", my_denom_df, 
                        " degrees of freedom, adjusted R-squared = ",  my_rsq_adj, ".")

anova_table <- data.frame(summary(m1)$coefficients)
names(anova_table) <- c("Estimate", "SE", "t", "p")

anova_out <- list(anova_caption, anova_table)
names(anova_out) <- c("caption", "table")

write_rds(anova_out, file = paste0(out_path, "nestedness_anova_table.rds"))

kable(anova_table, caption = anova_caption, align = 'c')


```



```{r}
if(params$run_decay_analysis == FALSE ){
knitr::knit_exit()
}
```


## Zeta decay 
```{r, warning = FALSE, label='Zeta Distance Decay Mean Slopes'}
set.seed(1) 

zeta.ddecays <- Zeta.ddecays(xy = site.by.xy, site.by.species, sam = params$sam_ddecay, orders = params$orders_ddecay,
plot = TRUE, confint.level = 0.95)

write_rds(zeta.ddecays, file = paste0(out_path, params$dataset ,"_zeta_distance_decay.rds"))
```

```{r}

png(file = paste0(out_path, params$dataset, "_zeta_distance_decays.png"), pointsize=10, width=960, height=960, res=300)
Plot.zeta.ddecays(zeta.ddecays)
dev.off()

```


```{r, warning = FALSE, label='Zeta Distance Decay GAMs'}
set.seed(1) 
zeta.ddecay.gam. <- Zeta.ddecay(xy = site.by.xy, data.spec = site.by.species, order = 2, 
                                    reg.type="gam")

set.seed(1) 
zeta.ddecay.gam. <- Zeta.ddecay(xy = site.by.xy, data.spec = site.by.species, order = 3, 
                                    reg.type="gam")

set.seed(1) 
zeta.ddecay.gam. <- Zeta.ddecay(xy = site.by.xy, data.spec = site.by.species, order = 6, 
                                    reg.type="gam")

set.seed(1) 
zeta.ddecay.gam. <- Zeta.ddecay(xy = site.by.xy, data.spec = site.by.species, order = 10, 
                                    reg.type="gam")

if (max(params$orders_ddecay) >= 20){
set.seed(1) 
zeta.ddecay.gam. <- Zeta.ddecay(xy = site.by.xy, data.spec = site.by.species, order = 20, 
                                    reg.type="gam")
}

if (max(params$orders_ddecay) >= 50){
set.seed(1) 
zeta.ddecay.gam. <- Zeta.ddecay(xy = site.by.xy, data.spec = site.by.species, order = 50, 
                                    reg.type="gam")
}

if (max(params$orders_ddecay) >= 100){
set.seed(1) 
zeta.ddecay.gam. <- Zeta.ddecay(xy = site.by.xy, data.spec = site.by.species, order = 100, 
                                    reg.type="gam")
}
```







